### ISSUE TITLE
Error caused by something in this stage text

### ISSUE THREAD

**Issue by MjnMixael** [asarium/libRocketMod#4]
The error is `LUA ERROR: [string "rocket_util.lua"]:70: attempt to perform arithmetic on local 'rangeEndStart' (a nil value)`

Here is the relevant stage text.

> $b * $b GTD $b Intrepid
> $b * $b Beta $b Aquilae $b System
> $b * $b 07/08/36
> 
> $b Your $b new $b Assignment
> 
> Pilots, I'm $b Admiral $b Po$| . I'd like to welcome all former $r GTI personnel returning to active service. I know it's been a long year of investigations, and it hasn't been easy on any of us. The rebellion was widespread within the $r GTI$| , but your return means that you have been cleared for duty. This marks a special day pilots, a day when we can return to the foundations of our $b Galactic $b Terran $b Alliance and work together again.
> 
> You will be assigned to the $b 47th $b Cutthroats$| , a special ops squadron aboard the $g GTD $g Intrepid$| . Because of your experience and qualifications, your squadron will have multiple roles ranging from escort and raids to intelligence and priority capture.

**Comment by asarium** [comment]
Should be fixed in the latest version. I did not handle ending the line with a color tag properly...
